### ISSUE TITLE
Syntx error

### ISSUE THREAD

**Issue by Indeserpen** [anoduck/recon-ng#1]
Hello!

Lately i,m getiin some syntax error when run recon-ng! Error output: 
[recon-ng][default] > workspaces add ccbank
[!] SyntaxError: invalid syntax.
[!] Module 'recon/domains-hosts/brute_hosts' disabled.
[!] SyntaxError: invalid syntax.
[!] Module 'recon/hosts-hosts/reverse_resolve' disabled.
[!] SyntaxError: invalid syntax.
[!] Module 'recon/hosts-hosts/resolve' disabled.
[!] SyntaxError: invalid syntax.
[!] Module 'recon/domains-domains/brute_suffix' disabled.
[!] SyntaxError: invalid syntax.
[!] Module 'recon/netblocks-hosts/reverse_resolve' disabled.

I tried apt-get remove recon-ng && apt-get update && apt-get install recon-ng, did not fixed error!
Running on kali linux rolling edition!

**Comment by anoduck** [comment]
Recon-ng version is deprecated, and should not be used.
